# Generated by Django 5.1.4 on 2025-01-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
